package safe

type AddForm struct {
	IdNumber string `json:"id_number"`
	Mapping  string `json:"mapping"`
	Token    string `json:"token"`
}

type QuesForm struct {
	JCJSSJ        string `json:"JCJSSJ"`
	FJCC          string `json:"FJCC"`
	GLDD          string `json:"GLDD"`
	RESOURCEID    string `json:"RESOURCE_ID"`
	LKHBJTGJ      string `json:"LKHBJTGJ"`
	TW2           string `json:"TW2"`
	TW1           string `json:"TW1"`
	TW3           string `json:"TW3"`
	JHFJJT        string `json:"JHFJJT"`
	SZLY          string `json:"SZLY"`
	JHFJRQ        string `json:"JHFJRQ"`
	SZSS          string `json:"SZSS"`
	JSDW5         string `json:"JSDW5"`
	JSDW4         string `json:"JSDW4"`
	FJRQ          string `json:"FJRQ"`
	SFJHFJTEXT    string `json:"SFJHFJ_TEXT"`
	JSDW6         string `json:"JSDW6"`
	RYLZNLTEXT    string `json:"RYLZNL_TEXT"`
	JSSFLJ        string `json:"JSSFLJ"`
	IP            string `json:"IP"`
	FKID          string `json:"FK_ID"`
	LKHBCC        string `json:"LKHBCC"`
	JSDW1         string `json:"JSDW1"`
	JSDW3         string `json:"JSDW3"`
	JSDW2         string `json:"JSDW2"`
	GKSYD         string `json:"GKSYD"`
	LBID          string `json:"LBID"`
	FJQSZS        string `json:"FJQSZS"`
	JSFJRQ        string `json:"JSFJRQ"`
	JSQX1         string `json:"JSQX1"`
	JSQX3         string `json:"JSQX3"`
	JSFJJTGJTEXT  string `json:"JSFJJTGJ_TEXT"`
	JSQX2         string `json:"JSQX2"`
	JHFJCC        string `json:"JHFJCC"`
	JSQX5         string `json:"JSQX5"`
	JSFJQSZSTEXT  string `json:"JSFJQSZS_TEXT"`
	JSQX4         string `json:"JSQX4"`
	JSQX6         string `json:"JSQX6"`
	LOCATION      string `json:"LOCATION"`
	JSFJQSZS      string `json:"JSFJQSZS"`
	JTCYJKZKTEXT  string `json:"JTCYJKZK_TEXT"`
	LKHBRQ        string `json:"LKHBRQ"`
	FJQSZSX       string `json:"FJQSZSX"`
	DISTRICT      string `json:"DISTRICT"`
	DA2           string `json:"DA2"`
	JSFJYY        string `json:"JSFJYY"`
	PKID          string `json:"PK_ID"`
	DA1           string `json:"DA1"`
	FDY           string `json:"FDY"`
	SFGL          string `json:"SFGL"`
	RYLZNL        string `json:"RYLZNL"`
	MQSFZJ        string `json:"MQSFZJ"`
	MQSFZJTEXT    string `json:"MQSFZJ_TEXT"`
	SQCS          string `json:"SQCS"`
	JSRS          string `json:"JSRS"`
	JRSTZK        string `json:"JRSTZK"`
	JTCYJKZK      string `json:"JTCYJKZK"`
	MQSZQX        string `json:"MQSZQX"`
	CITY          string `json:"CITY"`
	TW3TEXT       string `json:"TW3_TEXT"`
	JTSFDX        string `json:"JTSFDX"`
	JHFJYY        string `json:"JHFJYY"`
	HJQJSFLJ      string `json:"HJQJSFLJ"`
	DWFS          string `json:"DWFS"`
	LKHBJTGJTEXT  string `json:"LKHBJTGJ_TEXT"`
	TW2TEXT       string `json:"TW2_TEXT"`
	JSRSTEXT      string `json:"JSRS_TEXT"`
	SZXY          string `json:"SZXY"`
	JTSFDXTEXT    string `json:"JTSFDX_TEXT"`
	NATION        string `json:"NATION"`
	JHFJJTTEXT    string `json:"JHFJJT_TEXT"`
	SFJCGHBRQ     string `json:"SFJCGHBRQ"`
	SFQGHBTEXT    string `json:"SFQGHB_TEXT"`
	TW1TEXT       string `json:"TW1_TEXT"`
	XNZZ          string `json:"XNZZ"`
	JSFJJTGJ      string `json:"JSFJJTGJ"`
	JRRQ          string `json:"JRRQ"`
	FJQSZSTEXT    string `json:"FJQSZS_TEXT"`
	SFJCGHBRQTEXT string `json:"SFJCGHBRQ_TEXT"`
	JCQSSJ        string `json:"JCQSSJ"`
	JRSTZKTEXT    string `json:"JRSTZK_TEXT"`
	MQSZSX        string `json:"MQSZSX"`
	JRRQ2         string `json:"JRRQ2"`
	SFQGHB        string `json:"SFQGHB"`
	JSXM6         string `json:"JSXM6"`
	FJYY          string `json:"FJYY"`
	JSFJCCHB      string `json:"JSFJCCHB"`
	JSFJQXXZZ     string `json:"JSFJQXXZZ"`
	SZBJ          string `json:"SZBJ"`
	FJJTGJTEXT    string `json:"FJJTGJ_TEXT"`
	SFJHFJ        string `json:"SFJHFJ"`
	DSID          string `json:"DSID"`
	JSXM1         string `json:"JSXM1"`
	MQSZS         string `json:"MQSZS"`
	JSXM3         string `json:"JSXM3"`
	JSXM2         string `json:"JSXM2"`
	JSXM5         string `json:"JSXM5"`
	JSXM4         string `json:"JSXM4"`
	SJH           string `json:"SJH"`
	MQSZSTEXT     string `json:"MQSZS_TEXT"`
	FJJTGJ        string `json:"FJJTGJ"`
	JSSFLJTEXT    string `json:"JSSFLJ_TEXT"`
	DSXM          string `json:"DSXM"`
	GLYY          string `json:"GLYY"`
	ZLQK          string `json:"ZLQK"`
	XSLX          string `json:"XSLX"`
	HJQJSFLJTEXT  string `json:"HJQJSFLJ_TEXT"`
	XH            string `json:"XH"`
	GKSYDTEXT     string `json:"GKSYD_TEXT"`
	ZJJTZZ        string `json:"ZJJTZZ"`
	XM            string `json:"XM"`
	PROVINCE      string `json:"PROVINCE"`
	BZR           string `json:"BZR"`
	MQSZG         string `json:"MQSZG"`
}

type SafeForm struct {
	Mapping      string `json:"mapping"`
	Token        string `json:"token"`
	Key          string `json:"key"`
	XM1          string `json:"XM1"`
	XH1          string `json:"XH1"`
	SZXY1        string `json:"SZXY1"`
	SZBJ1        string `json:"SZBJ1"`
	XSLX         string `json:"XSLX"`
	FDY1         string `json:"FDY1"`
	DSXM1        string `json:"DSXM1"`
	GKSYDTEXT    string `json:"GKSYD_TEXT"`
	GKSYD        string `json:"GKSYD"`
	SJH          string `json:"SJH"`
	SZLY         string `json:"SZLY"`
	SZSS         string `json:"SZSS"`
	SQCS         string `json:"SQCS"`
	JRRQ         string `json:"JRRQ"`
	JRSTZKTEXT   string `json:"JRSTZK_TEXT"`
	JRSTZK       string `json:"JRSTZK"`
	ZLQK         string `json:"ZLQK"`
	JTCYJKZKTEXT string `json:"JTCYJKZK_TEXT"`
	JTCYJKZK     string `json:"JTCYJKZK"`
	MQSFZJTEXT   string `json:"MQSFZJ_TEXT"`
	MQSFZJ       string `json:"MQSFZJ"`
	MQSZSTEXT    string `json:"MQSZS_TEXT"`
	MQSZS        string `json:"MQSZS"`
	MQSZSX       string `json:"MQSZSX"`
	MQSZQX       string `json:"MQSZQX"`
	SFJHFJTEXT   string `json:"SFJHFJ_TEXT"`
	SFJHFJ       string `json:"SFJHFJ"`
	JHFJRQ       string `json:"JHFJRQ"`
	JHFJJTTEXT   string `json:"JHFJJT_TEXT"`
	JHFJJT       string `json:"JHFJJT"`
	JHFJCC       string `json:"JHFJCC"`
	JTSFDXTEXT   string `json:"JTSFDX_TEXT"`
	JTSFDX       string `json:"JTSFDX"`
	ZJJTZZ       string `json:"ZJJTZZ"`
	JSRSTEXT     string `json:"JSRS_TEXT"`
	JSRS         string `json:"JSRS"`
	JSSFLJTEXT   string `json:"JSSFLJ_TEXT"`
	JSSFLJ       string `json:"JSSFLJ"`
	JSFJQSZSTEXT string `json:"JSFJQSZS_TEXT"`
	JSFJQSZS     string `json:"JSFJQSZS"`
	JSFJQXXZZ    string `json:"JSFJQXXZZ"`
	JSFJRQ       string `json:"JSFJRQ"`
	JSFJYY       string `json:"JSFJYY"`
	JSFJJTGJTEXT string `json:"JSFJJTGJ_TEXT"`
	JSFJJTGJ     string `json:"JSFJJTGJ"`
	JSFJCCHB     string `json:"JSFJCCHB"`
	HJQJSFLJTEXT string `json:"HJQJSFLJ_TEXT"`
	HJQJSFLJ     string `json:"HJQJSFLJ"`
	FJQSZSTEXT   string `json:"FJQSZS_TEXT"`
	FJQSZS       string `json:"FJQSZS"`
	FJQSZSX      string `json:"FJQSZSX"`
	FJRQ         string `json:"FJRQ"`
	FJJTGJTEXT   string `json:"FJJTGJ_TEXT"`
	FJJTGJ       string `json:"FJJTGJ"`
	FJCC         string `json:"FJCC"`
	FJYY         string `json:"FJYY"`
	MQSZG        string `json:"MQSZG"`
	DA1          string `json:"DA1"`
	DA2          string `json:"DA2"`
	SFGL         string `json:"SFGL"`
	GLYY         string `json:"GLYY"`
	GLDD         string `json:"GLDD"`
	TW1TEXT      string `json:"TW1_TEXT"`
	TW1          string `json:"TW1"`
	TW2TEXT      string `json:"TW2_TEXT"`
	TW2          string `json:"TW2"`
	TW3TEXT      string `json:"TW3_TEXT"`
	TW3          string `json:"TW3"`
	JSXM1        string `json:"JSXM1"`
	JSDW1        string `json:"JSDW1"`
	JSQX1        string `json:"JSQX1"`
	JSXM2        string `json:"JSXM2"`
	JSDW2        string `json:"JSDW2"`
	JSQX2        string `json:"JSQX2"`
	JSXM3        string `json:"JSXM3"`
	JSDW3        string `json:"JSDW3"`
	JSQX3        string `json:"JSQX3"`
	JSXM4        string `json:"JSXM4"`
	JSDW4        string `json:"JSDW4"`
	JSQX4        string `json:"JSQX4"`
	JSXM5        string `json:"JSXM5"`
	JSDW5        string `json:"JSDW5"`
	JSQX5        string `json:"JSQX5"`
	JSXM6        string `json:"JSXM6"`
	JSDW6        string `json:"JSDW6"`
	JSQX6        string `json:"JSQX6"`
}
